### ISSUE TITLE
Error while install this package

### ISSUE THREAD

**Issue by faizanvahevaria** [staruml/metadata-json#5]
Hello i am getting error while installing this package in my node project.
---------------------
Error
---------------------
>sudo npm i metadata-json
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5

> canvas@1.3.12 install /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas/build'
gyp ERR! System Linux 4.18.0-25-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN gs-gs.staruml-cefact@0.2.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vi109/.npm/_logs/2019-07-29T05_59_24_991Z-debug.log

**Comment by niklauslee** [comment]
Try with `--unsafe-perm=true` option

**Comment by faizanvahevaria** [comment]
> Try with `--unsafe-perm=true` option

I have tried with it. But still i am getting errors.
---------------------------------------------------------------
npm i metadata-json --unsafe-perm=true
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5

> canvas@1.3.12 install /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas
> node-gyp rebuild

make: Entering directory '/home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function ‘boolean empty_closure_output_buffer(j_compress_ptr)’:
../src/JPEGStream.h:42:108: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, argv);
                                                                                                            ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h: In function ‘void term_closure_destination(j_compress_ptr)’:
../src/JPEGStream.h:63:113: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, data_argv);
                                                                                                                 ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
In file included from ../src/Canvas.cc:20:0:
../src/JPEGStream.h:71:112: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)dest->closure->fn, 2, end_argv);
                                                                                                                ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:72:57: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   if (info[0]->IsNumber()) width = info[0]->Uint32Value();
                                                         ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:73:58: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   if (info[1]->IsNumber()) height = info[1]->Uint32Value();
                                                          ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:74:76: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   if (info[2]->IsString()) type = !strcmp("pdf", *String::Utf8Value(info[2]))
                                                                            ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:76:48: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     : !strcmp("svg", *String::Utf8Value(info[2]))
                                                ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Canvas::SetWidth(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/Canvas.cc:109:40: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     canvas->width = value->Uint32Value();
                                        ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_SETTER_RETURN_TYPE Canvas::SetHeight(v8::Local<v8::String>, v8::Local<v8::Value>, Nan::NAN_SETTER_ARGS_TYPE)’:
../src/Canvas.cc:130:41: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     canvas->height = value->Uint32Value();
                                         ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc: In static member function ‘static void Canvas::ToBufferAsyncAfter(uv_work_t*)’:
../src/Canvas.cc:211:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     closure->pfn->Call(1, argv);
                               ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/Canvas.cc:216:31: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     closure->pfn->Call(2, argv);
                               ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:254:52: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
           compression_level = info[1]->Uint32Value();
                                                    ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:259:49: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             uint32_t tmp = info[1]->Uint32Value();
                                                 ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:281:39: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         filter = info[2]->Uint32Value();
                                       ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:325:14: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
     TryCatch try_catch;
              ^~~~~~~~~
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note: candidate: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^~~~~~~~
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note:   candidate expects 1 argument, 0 provided
../src/Canvas.cc: In function ‘cairo_status_t streamPNG(void*, const uint8_t*, unsigned int)’:
../src/Canvas.cc:357:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure->fn, 3, argv);
                                                                                                      ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:376:52: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
           compression_level = info[1]->Uint32Value();
                                                    ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:381:49: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             uint32_t tmp = info[1]->Uint32Value();
                                                 ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:403:39: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         filter = info[2]->Uint32Value();
                                       ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:417:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
   TryCatch try_catch;
            ^~~~~~~~~
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note: candidate: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^~~~~~~~
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note:   candidate expects 1 argument, 0 provided
../src/Canvas.cc:426:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/Canvas.cc:432:103: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), (v8::Local<v8::Function>)closure.fn, 1, argv);
                                                                                                       ^
In file included from ../src/Canvas.h:22:0,
                 from ../src/Canvas.cc:7:
../../nan/nan.h:1024:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/Canvas.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamJPEGSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Canvas.cc:458:12: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
   TryCatch try_catch;
            ^~~~~~~~~
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note: candidate: v8::TryCatch::TryCatch(v8::Isolate*)
   explicit TryCatch(Isolate* isolate);
            ^~~~~~~~
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:8536:12: note:   candidate expects 1 argument, 0 provided
../src/Canvas.cc:459:64: warning: ‘double v8::Value::NumberValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   write_to_jpeg_stream(canvas->surface(), info[0]->NumberValue(), info[1]->NumberValue(), info[2]->BooleanValue(), &closure);
                                                                ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2475:45: note: declared here
   V8_DEPRECATED("Use maybe version", double NumberValue() const);
                                             ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc:459:88: warning: ‘double v8::Value::NumberValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   write_to_jpeg_stream(canvas->surface(), info[0]->NumberValue(), info[1]->NumberValue(), info[2]->BooleanValue(), &closure);
                                                                                        ^
In file included from /home/vi109/.node-gyp/10.16.0/include/node/v8.h:26:0,
                 from ../src/Canvas.h:11,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:2475:45: note: declared here
   V8_DEPRECATED("Use maybe version", double NumberValue() const);
                                             ^
/home/vi109/.node-gyp/10.16.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/Canvas.cc: In member function ‘void Canvas::resurface(v8::Local<v8::Object>)’:
../src/Canvas.cc:542:85: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Context2d *context2d = Nan::ObjectWrap::Unwrap<Context2d>(context->ToObject());
                                                                                     ^
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
../src/Canvas.cc:559:85: warning: ‘v8::Local<v8::Object> v8::Value::ToObject() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         Context2d *context2d = Nan::ObjectWrap::Unwrap<Context2d>(context->ToObject());
                                                                                     ^
In file included from ../src/Canvas.h:11:0,
                 from ../src/Canvas.cc:7:
/home/vi109/.node-gyp/10.16.0/include/node/v8.h:10046:15: note: declared here
 Local<Object> Value::ToObject() const {
               ^~~~~
canvas.target.mk:133: recipe for target 'Release/obj.target/canvas/src/Canvas.o' failed
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory '/home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.18.0-25-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vi109/Faizan-Vahevaria/StarUML/staruml-cefact/node_modules/canvas
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN gs-gs.staruml-cefact@0.2.2 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.3.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.3.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vi109/.npm/_logs/2019-07-31T05_49_01_235Z-debug.log
---------------------------------------------------------------
